default: &default
  cloud_name: "drew-templeton"
  api_key: "567231948876525"
  api_secret: QmbmFLBXi_bDY4dugHOMEXFqfQg
  enhance_image_tag: true
  static_image_support: true
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
